//* Login
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const LIMPIAR_USER = 'LIMPIAR_USER'

//* Inventario
export const MOSTRAR_INVENTARIOS = 'MOSTRAR_INVENTARIOS'
export const MOSTRAR_INVENTARIO_UNICO = 'MOSTRAR_INVENTARIO_UNICO'
export const AGREGAR_INVENTARIO = 'AGREGAR_INVENTARIO'
export const EDITAR_INVENTARIO = 'EDITAR_INVENTARIO'
export const ELIMINAR_INVENTARIO = 'ELIMINAR_INVENTARIO'
export const LIMPIAR_INVENTARIO = 'LIMPIAR_INVENTARIO'
export const ERROR_INVENTARIO = 'ERROR_INVENTARIO'

//* Productos 
export const MOSTRAR_PRODUCTOS = "MOSTRAR_PRODUCTOS"
export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const ERROR_PRODUCTO = "ERROR_PRODUCTO";
export const LIMPIAR_PRODUCTOS = "LIMPIAR_PRODUCTOS"
export const ACTUALIZAR_PRODUCTO = "ACTUALIZAR_PRODUCTO";
export const MOSTRAR_PRODUCTO_UNICO = "MOSTRAR_PRODUCTO_UNICO";
export const ELIMINAR_PRODUCTOS = "ELIMINAR_PRODUCTOS";

//* Distribuidores
export const VER_DISTRIBUIDORES_SUCCESS = "VER_DISTRIBUIDORES_SUCCESS";

//* Puntos
export const MOSTRAR_PUNTOS = "MOSTRAR_PUNTOS";
export const LIMPIAR_PUNTOS = "LIMPIAR_PUNTOS";
export const FETCH_REGISTROPUNTOS_SUCCESS = "FETCH_REGISTROPUNTOS_SUCCESS";
export const ERROR_PUNTO = "ERROR_PUNTO";
export const ACTUALIZAR_PUNTO = "ACTUALIZAR_PUNTO";
export const MOSTRAR_PUNTO_UNICO = "MOSTRAR_PUNTO_UNICO";
export const ELIMINAR_PUNTOS = "ELIMINAR_PUNTOS";
export const AGREGAR_PUNTO = "AGREGAR_PUNTO";

//* Registro de Productos 
export const FETCH_REGISTROPRODUCTOS_SUCCESS = "FETCH_REGISTROPRODUCTOS_SUCCESS";
export const FETCH_REGISTROPRODUCTOS_ERROR = "FETCH_REGISTROPRODUCTOS_ERROR";


//* Actualizar Productos
export const UPDATE_PRODUCTOS = "UPDATE_PRODUCTOS";
export const SINGLE_PRODUCTOS = "SINGLE_PRODUCTOS";



//* Actualizar Puntos
export const UPDATE_PUNTOS = "UPDATE_PUNTOS";
export const SINGLE_PUNTOS = "SINGLE_PUNTOS";






